date.format             = dd-MM-yyyy HH:mm:ss
timezone                = Europe/Samara

dns.local.port  = 53
proxy.local.port = 8888
dns.list        = 77.88.8.8,8.8.8.8,8.8.4.4,77.88.8.1
dns.start       = true
proxy.start       = true
Config.reload.timeout        = 300
dns.thread.num  = 50
dns.timeout     = 3